# Generated by Django 4.2.25 on 2026-03-22 12:57

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='commentarypost',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='post',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='post',
            name='subject',
            field=models.CharField(choices=[('Partage d’expérience', 'Partage d’expérience'), ('Demande d’aide', 'Demande d’aide'), ('Sondage', 'Sondage'), ('Proposition', 'Proposition'), ('Autre', 'Autre')], default='Autre', max_length=20),
        ),
    ]
