from django.urls import path, include
# Imports the default router from Django REST Framework.
from rest_framework.routers import DefaultRouter
from .views import PostViewSet, CommentaryPostViewSet

# Take care of generating REST routes automatically from registered ViewSets
router = DefaultRouter()
# r'posts': this is the URL prefix (for example : /posts/)
# PostViewSet is View class that handles this route and this will create all routes related to post
router.register(r'posts', PostViewSet)
# r'commentaries': this is the URL prefix (for example : /commentaries/)
# CommentaryPostViewSet is View class that handles this route and this will create all routes related to CommentaryPost
router.register(r'commentaries', CommentaryPostViewSet)

urlpatterns = [
    # Indicates that all routes generated by the router should be included in the root of the app, which means /posts/ and /commentaries/.
    path('', include(router.urls)),
]
